/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    uint32_t *pClkCtrlReg =   (uint32_t*)0x40023830;
    uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
    uint32_t *pPortAModeReg = (uint32_t*)0x40020000;
    uint32_t *pPortDOutReg =  (uint32_t*)0x40020C14;
    uint32_t *pPortAInReg =   (uint32_t*)0x40020010;
    *pClkCtrlReg |= (1 << 3);
    *pClkCtrlReg |= (1 << 0);
    *pPortDModeReg &= ~(3 << 24);
    *pPortDModeReg |= (1 << 24);

    *pPortAModeReg &= ~(3 << 0);


    while(1)
    {
    	uint32_t pinValue = (uint32_t)(*pPortAInReg & 0x01);
		if(pinValue)
		{
			*pPortDOutReg |= (1 << 12);
		}
		else
		{
			*pPortDOutReg &= ~(1 << 12);
		}
    }
}
